name: Build Firmware

# The workflow will run on every push and pull request to the repository
on:
  - push
  - pull_request

jobs:
  build-firmware:
    runs-on: ubuntu-latest

    steps:
      # This step makes the contents of the repository available to the workflow
      - name: Checkout repository
        uses: actions/checkout@v5

      # For more information: https://github.com/arduino/compile-sketches#readme
      - name: Compile sketch
        uses: mar0x/compile-sketches@v1
        with:
          fqbn: arduino:avr:leonardo
          sketch-paths: ./firmware/
          libraries: |
            -
          verbose: true
          cli-compile-flags: |
            - --build-path
            - ${{ github.workspace }}/firmware/build
            - --build-property
            - compiler.c.elf.extra_flags=-g
            - --build-property
            - build.usb_manufacturer="MVR-Electronic.ru"
            - --build-property
            - build.usb_product="MIDI Controller"

      - name: Upload firmware
        uses: actions/upload-artifact@v7
        with:
          name: midi-controller-firmware
          path: ${{ github.workspace }}/firmware/build/*

      - name: Set up Node.js
        uses: actions/setup-node@v7
        with:
          cache: npm
          cache-dependency-path: ./client/controller-client

      - name: Install Dependencies
        run: npm ci
        working-directory: ./client/controller-client

      - name: Build Project
        run: npm run build
        working-directory: ./client/controller-client

      - name: Upload client
        uses: actions/upload-artifact@v7
        with:
          name: midi-controller-client
          path: ./client/controller-client/dist
